# Generated by Django 5.1.2 on 2025-02-08 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_me',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
